modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="nations"
version="1.0.0"
displayName="Nations Mod"
description="Towns, Nations, Claims, Wars"

# Зависимость от Minecraft
[[dependencies.nations]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

# Зависимость от Forge
[[dependencies.nations]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

# Зависимость от Dynmap (ВАЖНО: mandatory=false)
[[dependencies.nations]]
modId="dynmap"
mandatory=false
versionRange="[3.0,)"
ordering="AFTER"
side="BOTH"
